Prevent postgres errors when reporting datalayer
scalableminds/webknossos pull request #4946
Opened 2020-11-15 18:46 UTC by youri-k

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- abc

### Issues:
- fixes #4483 

------
- [ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [ ] Ready for review

2020-11-19 10:43 UTC, youri-k commented
I found the the SQL Error when uploading a zero-layer dataset.
Sadly, I cannot reproduce the `p_key` bug locally, even after reintroducing an absent dataset.
I noticed that the serializable level was not set like in other composed queries, so I suggest trying this and see if it still happens in production.

2020-11-22 08:08 UTC, fm3 requested changes
Cool, thanks for looking into that :) Also thanks for fixing the formatting!
Since you said you could not reproduce the duplicate key error, I’d keep the original issue open until we’ve found a new clue there or until we are sure that it does not occur again. Instead, we can remove the line about zero-layer datasets from the original issue.

2020-11-22 08:08 UTC, fm3 commented on app/models/binary/DataSet.scala
> +      _ <- run(DBIO.sequence(List(clearQuery) ++ insertQueries).transactionally.withTransactionIsolation(Serializable))
I believe anything that is run as `Serializable` aborts on conflict, so we should probably add a retry around it, as in the other places where this happens.

2020-11-22 08:08 UTC, fm3 commented on app/models/binary/DataSet.scala
> +    // TODO if we redefine dataSet.usable, this can be changed back
please move this todo line to the relevant issue instead

2020-11-26 09:47 UTC, fm3 approved these changes
LGTM

2020-11-26 12:33 UTC, merged