Update issue templates
scalableminds/webknossos pull request #5121
Opened 2021-02-03 09:39 UTC by hotzenklotz

2021-02-03 10:35 UTC, philippotto approved these changes

2021-02-03 11:12 UTC, normanrz requested changes

2021-02-03 11:12 UTC, normanrz commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
```suggestion
labels: bug
```

2021-02-03 11:12 UTC, normanrz commented on .github/ISSUE_TEMPLATE/feature_request.md
> +labels: ''
```suggestion
labels: enhancement
```

2021-02-03 11:49 UTC, hotzenklotz commented
@MichaelBuessemeyer or @philippotto Feel free to take over the PR and add the relevant issue templates content.

2021-02-05 08:37 UTC, MichaelBuessemeyer commented
I just updated the templates to the content we had before. If everyone is happy we can merge this PR :)

2021-02-05 12:08 UTC, normanrz approved these changes

2021-02-05 12:20 UTC, philippotto commented
:+1:

2021-02-08 08:48 UTC, merged