WIP: Store credentials separately
scalableminds/webknossos pull request #6646
Opened 2022-11-17 11:07 UTC by frcroth

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- abc

### Issues:
- fixes #6612

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Needs datastore update after deployment
- [ ] Ready for review

2022-12-05 16:41 UTC, frcroth commented
Waiting for #6679 to fix the s3 file system.

2023-01-03 09:05 UTC, fm3 requested changes
Cool stuff, works really well :) I added a few refactoring comments, but nothing major.

2023-01-03 14:04 UTC, fm3 commented on app/models/binary/credential/Credential.scala
> +                      scope: Option[String],
scope is no longer included, right?

2023-01-05 13:00 UTC, frcroth commented on webknossos-datastore/app/com/scalableminds/webknossos/datastore/storage/FileSystemCredentials.scala
> +}
Yes

```
[error] /home/felix/scm/webknossos/webknossos-datastore/app/com/scalableminds/webknossos/datastore/services/DSRemoteWebKnossosClient.scala:130:27: No Json deserializer found for type com.scalableminds.webknossos.datastore.storage.AnyCredential. Try to implement an implicit Reads or Format for this type.
[error]       .getWithJsonResponse[AnyCredential]
[error]                           ^
[error] one error found
[error] (webknossosDatastore / Compile / compileIncremental) Compilation failed
```

2023-01-10 10:43 UTC, fm3 approved these changes
LGTM :) Please have a look at the merge conflicts, including evolution numbering.

Note that refresh-schema will delete the stored credentials for local datasets, so streaming test datasets become unusable then. I’m not sure how to manage this for our local development. May not be a serious problem. The old format still works, right? So maybe we could manually edit the json for a local dataset to include the credentials again, to keep it locally for testing across schema refreshs.

2023-01-17 10:15 UTC, merged