Update deprecated antd <Menu>
scalableminds/webknossos pull request #6860
Opened 2023-02-20 14:53 UTC by hotzenklotz

We regularly have depreacation warning in the browser dev tools that antd's `<Menu>{children}</Menu>` HOC has been replaced with an `items` prop: `<Menu items={...}>`. 

The recommend upgrade path from antd v4 to v5 is to fix all these deprecation warnings. In this pull request I fixed the `<Navbar>` and `<FolderTree>` menus.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Click on all navbar menu items. to make sure that they still work
- Consider styling changes (menu should look the same)

### Issues:
- fixes #6812

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

2023-02-20 15:37 UTC, hotzenklotz commented
Mhm, I just realized that this CI error did not occur locally since I already upgrade to the latest antd v4.28.x locally. It seems like the `menu` prop was introduced in the meantime:

https://app.circleci.com/pipelines/github/scalableminds/webknossos/10348/workflows/6838ef9d-90ac-4362-95fa-73319c4572ae/jobs/21737

2023-02-21 16:17 UTC, philippotto requested changes
Thank you for taking care of the deprecations :1st_place_medal: 

The code looks good mostly and testing went well, too. However, when making the browser window quite small, there is an unnecessary large margin here:

![image](https://user-images.githubusercontent.com/2486553/220400331-233a6258-368b-49e2-8923-a98aae490bac.png)

2023-02-21 16:17 UTC, philippotto commented on frontend/javascripts/navbar.tsx
> +  const helSubMenuItems: ItemType[] = [
should be `helpSubMenuItems`

2023-02-21 16:17 UTC, philippotto commented on frontend/javascripts/navbar.tsx
> +          // className="sub-menu-without-padding vertical-center-flex-fix"
can this be removed?

2023-02-22 09:13 UTC, hotzenklotz commented
Thanks for the review. I applied your feedback.

2023-02-22 12:57 UTC, philippotto commented on frontend/javascripts/navbar.tsx
> -    return <span title={title}>{icon}</span>;
I think this is still missing? There are no tooltips in the tracing view with a small screen (see screenshot):
![image](https://user-images.githubusercontent.com/2486553/220625845-e5169b0a-25be-440a-b906-901771609f7d.png)

2023-02-22 12:58 UTC, philippotto commented on frontend/javascripts/navbar.tsx
> +          // className="sub-menu-without-padding vertical-center-flex-fix"
:wastebasket: probably?

2023-02-22 14:12 UTC, hotzenklotz commented on frontend/javascripts/navbar.tsx
> -    return <span title={title}>{icon}</span>;
I added a <ToolTip>. Should be fixed now.

2023-02-22 15:47 UTC, philippotto approved these changes
Great :+1:

2023-02-22 15:51 UTC, merged