Add Super admin routes for user and orga management
scalableminds/webknossos pull request #7196
Opened 2023-07-10 12:33 UTC by frcroth

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- abc

### Issues:
- fixes #7148

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

2023-07-12 07:17 UTC, fm3 requested changes
Thanks for having a look at this!

I think your version works well, but it could be simplified and be made more feature-complete by reusing some of the existing methods used during user signup/organization switching. I added some comments pointing to those. 

Maybe you could have a look at that? Feel free to reorganize some of those, if it makes things easier, none of this is set in stone :)

We might even alter the existing routes (of course then we would have to adapt the frontend).

2023-07-17 07:40 UTC, frcroth commented on app/controllers/OrganizationController.scala
> +      } yield Ok(user._id.toString)
Just used the specification in the issue

2023-07-17 07:45 UTC, fm3 commented on app/controllers/OrganizationController.scala
> +      } yield Ok(user._id.toString)
Fair enough ;) However, if you’re ok with it, let’s just support email

2023-07-17 12:10 UTC, frcroth commented on conf/webknossos.latest.routes
> +POST          /organizations                                                                    controllers.OrganizationController.create
But this route always seems to create a new user? I understood that the new route should create an org with an existing user

2023-07-17 12:34 UTC, fm3 commented on conf/webknossos.latest.routes
> +POST          /organizations                                                                    controllers.OrganizationController.create
Maybe I misunderstood the requirement then. @normanrz Could you clarify what you need here?

2023-07-17 16:11 UTC, normanrz commented on conf/webknossos.latest.routes
> +POST          /organizations                                                                    controllers.OrganizationController.create
> * Create a new organization (with organization name, owner user email/id)

I think what is missing is creating a new org for an existing user. For a new user, we can just use the signup.

2023-07-20 10:59 UTC, fm3 reviewed
Almost there :)

2023-07-20 10:59 UTC, fm3 commented on app/controllers/OrganizationController.scala
> +        _ <- userService.joinOrganization(user, org._id, autoActivate = true, isAdmin = true)
```suggestion
        _ <- userService.joinOrganization(user, org._id, autoActivate = true, isAdmin = true, isOwner = true)
```
(should be propagated to the user’s isOrganizationOwner field)

2023-07-20 10:59 UTC, fm3 commented on app/models/user/UserService.scala
> +    } yield ()
```suggestion
Fox.assertTrue(multiUserDAO.findOne(multiUserId).map(_.isSuperUser))
```
(could you try that? I think that’s the same but maybe I’m overlooking something)

2023-07-20 10:59 UTC, fm3 commented on conf/messages
> +user.id.orEmailNecessary=Email or id needed to identify user.
probably unused now?

2023-07-24 11:36 UTC, merged