WIP: Add Render Animation Worker Job
scalableminds/webknossos pull request #7348
Opened 2023-09-19 12:10 UTC by fm3

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- abc

### TODOs:
- [ ] ...

### Issues:
- fixes #

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

2023-10-17 08:09 UTC, hotzenklotz commented on frontend/javascripts/oxalis/view/action-bar/tracing_actions_view.tsx
> +    if (activeUser?.isSuperUser) {
This is by design. Let's do a soft launch and try some larger datasets on the server first before releasing this publicly.

2023-10-17 08:12 UTC, hotzenklotz commented
@philippotto I think this is ready for review. Feel free to only review the WK side. In case you setup up the worker too, perhaps you can do a rough review for that as well. Thanks.

I will create a page for the WK documentation later this week in a separate PR. Let's try to get this merged and soft launched for super users so that we can iron out any issue with the worker deployment and test performance in the real world.

2023-10-17 09:03 UTC, fm3 commented
I’d say the backend changes are straightforward enough that they don’t require a specialized review. @philippotto maybe you could quickly read through them as well while checking the front-end

2023-10-17 14:18 UTC, philippotto requested changes
awesome stuff :+1: only left a couple of nitpicks.

also, one thing UX wise: I'd put the word "video" somewhere to clarify that the output medium is a video file. otherwise, it might be unclear to the user what they will get (a gif? a blender file? an upload to youtube?).

2023-10-17 14:18 UTC, philippotto commented on frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
> +              For custom animations, please{" "}
I'd elaborate here a bit (e.g., mention custom camera paths etc).

2023-10-17 14:18 UTC, philippotto commented on frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
> +    const [_, estimated_texture_size] = selectMagForTextureCreation(
please use camel case here

2023-10-17 14:18 UTC, philippotto commented on frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
> +    const isTooManyMeshes = meshSegmentIds.length > 30;
please extract the 30 into a top level constant (also use that in line 147)

2023-10-17 14:18 UTC, philippotto commented on frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
> +    let meshSegmentIds = [] as number[];
```suggestion
    let meshSegmentIds: number[] = [];
```

2023-10-17 14:18 UTC, philippotto commented on frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
> +    const [intensityMin, intensityMax] = intensityRange || defaultIntensityRange;
can you refactor this into a `getEffectiveIntensityRange(dataset, layerName, datasetConfiguration)` auxiliary accessor. Could be added to dataset_accessors.ts.

2023-10-18 08:42 UTC, philippotto commented
> I’d say the backend changes are straightforward enough that they don’t require a specialized review. @philippotto maybe you could quickly read through them as well while checking the front-end

I did that yesterday, too, and everything looked good to me :)

2023-10-18 15:17 UTC, hotzenklotz commented
@fm3 Did you built email notifications for this job as well?

2023-10-19 07:46 UTC, fm3 commented
I did not adapt the email code, no. My understanding is that a generic job completed email will be sent? Feel free to add a specialized email though :) Or I could do it as well if you tell me what it should say

2023-10-19 07:48 UTC, fm3 commented on frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
> +    let segmentationLayerName = "segmentatation";
If this is optional then I’d say the backend should also understand that. I can probably add that today.

2023-10-19 07:48 UTC, hotzenklotz commented
> I did not adapt the email code, no. My understanding is that a generic job completed email will be sent? Feel free to add a specialized email though :) Or I could do it as well if you tell me what it should say

I haven't tried the email notifications on my local dev setup (not configured). Let's start a soft launch and figure this out as well.

2023-10-19 09:18 UTC, fm3 commented on frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
> +    let segmentationLayerName = "segmentatation";
I rechecked the backend code, and there the type is `segmentationLayerName: Option[String]`, so it should be possible to make this optional in the frontend already.

2023-10-20 13:37 UTC, hotzenklotz commented on frontend/javascripts/oxalis/view/action-bar/create_animation_modal.tsx
> +    let segmentationLayerName = "segmentatation";
I switched the frontend values to `undefined` by default.

2023-10-20 13:47 UTC, philippotto approved these changes
Good stuff :+1:

2023-10-23 08:05 UTC, merged

2023-10-24 08:09 UTC, hotzenklotz commented
Follow Up Issue: [#3350](https://github.com/scalableminds/voxelytics/issues/3350)