WIP Refactor Skeletontree tab as Antd  <Tree /> component
scalableminds/webknossos pull request #7819
Opened 2024-05-22 14:28 UTC by hotzenklotz

In an effort to use the same antd `<Tree />` tree component for the skeletons, comments, and segments, I refactored the skeleton tab to use this component.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- abc

### TODOs:
- [ ] ...

### Issues:
- Contributes to #7765 

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

2024-06-05 11:07 UTC, MichaelBuessemeyer commented
Here is my pre-review testing feedback:
The tree items are too spacy:
This is the current master version which does not line break the tree names and thus is horizontally scrollable but more dense
![image](https://github.com/scalableminds/webknossos/assets/39529669/1e35cbea-a394-4e0e-87c9-f5f9bc09db88)
And this is your version:
![image](https://github.com/scalableminds/webknossos/assets/39529669/e3e7e74d-bca6-4379-ab5c-b977cd806c70)
I do prefer the dense (master) version


Rearranging trees within a group does no longer work on your branch.

Empty tree groups are opened by default on the master when: 
1. creating a new group and 
3. moving some trees into them. 

On your branch one needs to expand the group as step 3.

On the master, the level intend seems to be smaller (due to the missing drag handle). Is it possible to make this a little narrower to make the view more compact?



These are the thing I noticed during testing. So far it looks very good beside this few points :rocket:

2024-06-06 14:16 UTC, MichaelBuessemeyer reviewed
Please just re-request a review once its time :pray:  :)

2024-06-12 13:27 UTC, hotzenklotz commented on frontend/javascripts/oxalis/model/accessors/skeletontracing_accessor.ts
> +
Added some white space for readability.

2024-06-12 13:28 UTC, hotzenklotz commented on frontend/javascripts/oxalis/shaders/utils.glsl.ts
> +export const rgbaToCSS = (rgba: Vector4) => {
We save color values as RGBA, not HSLA. There is no reason to convert between the color models just for some CSS.

2024-06-12 13:30 UTC, hotzenklotz commented on frontend/javascripts/oxalis/view/right-border-tabs/tree_hierarchy_view.tsx
> -    if (prevState.prevProps == null || didTreeDataChange(prevState.prevProps, nextProps)) {
`didTreeDataChange` change has been replaces with `React.memo(<TreeHierarchyView/>)` at the very bottom of this file.

2024-06-12 13:32 UTC, hotzenklotz commented on frontend/javascripts/oxalis/view/right-border-tabs/tree_hierarchy_view.tsx
> +    return (
The `<Dropdown>` + menu moved here from old method `generateNodeProps()`

2024-06-12 13:34 UTC, hotzenklotz commented on frontend/javascripts/oxalis/view/right-border-tabs/tree_hierarchy_view_helpers.ts
> -    treeNode.isIndeterminate = treeNode.isChecked
The `indeterminate` state is not no longer directly controlled by use. Antd takes care of that.

2024-06-14 09:49 UTC, MichaelBuessemeyer requested changes
Overall everything looks very good :tada:. Thanks for implementing this.

I only found minor things. -> Please see my comments.

I additionally noticed, that when hovering a group or node a tooltip with the content `---` is shown. I was unable to identify what leads to this behaviour. Could you please investigate this and remove / hide this strange tooltip?

2024-07-01 13:57 UTC, hotzenklotz commented on frontend/javascripts/oxalis/view/right-border-tabs/tree_hierarchy_view.tsx
> -              disabled: !hasExpandedSubgroup,
Checking for subgroups on every render call is expensive. There is no real benefit from disabling these options. Having the ability to expand/collapse all groups is always a good feature regardless if does anything on selection.

2024-07-01 13:59 UTC, hotzenklotz commented on frontend/javascripts/oxalis/view/right-border-tabs/tree_hierarchy_view.tsx
> +      setExpandedNodeKeys([...expandedNodeKeys, selectedGroupIdKey, ...subGroupKeys]);
Done

2024-08-05 08:19 UTC, philippotto commented
Really looking forward to see this merged! I tested this PR for a bit and found some things:

- [ ] the scroll bar is not visible in dark mode (because the background color of the scroll bar is too dark?). in light mode, it works fine
- [ ] when selecting a tree, it is always scrolled to be at the top of the view (maybe both points can be solved with `scrollTo({..., align: "auto"})`?
  - [ ] when manually selecting an item from the list, this is very annoying, because the tree item was perfectly visible, anyway.
  - [ ] when selecting a tree/node in the data viewport, this auto-scroll behavior also always enforces the item to be at the top of the view (if the list is long enough). however, when the item was visible anyway, it's not necessary to scroll at all. 

won't fix?
- if a tree name is very long, you cannot scroll horizontally. apparently, this is a limitation of antd. so probably a won't fix. the full name can be seen via the tooltip or the rename-field.

2024-08-05 08:56 UTC, philippotto commented
Hmm, I found another thing:

- [ ] shift select often doesn't work. could it be that it performs the range by sorting alphabetically? however, the visible sorting might be by creation time. in the screenshot, the blue item was active and I shift-clicked on the gray item. nothing happens in that case

![image](https://github.com/user-attachments/assets/9136e047-a8b6-455f-bb29-303f1d58145a)

2024-08-05 16:05 UTC, MichaelBuessemeyer commented
Please wait until the backend changes of this pr have been reviewed (they haven't been reviewed yet. See: https://github.com/scalableminds/webknossos/pull/7939#issuecomment-2269370736)

@normanrz Could you take over looking over these changes? There shouldn't be many changes.

2024-08-06 09:22 UTC, MichaelBuessemeyer approved these changes
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdTM3eXd6NGNkZm1saHF4Y25jMjQyZmN1a3c5ODRsMjUyOXB3MXIxbiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/d2Z9QYzA2aidiWn6/giphy.gif)

2024-08-06 12:16 UTC, merged

2024-08-06 12:24 UTC, daniel-wer commented on package.json
> -    "react-sortable-tree": "^2.8.0",
The day has finally come :tada: