Align sections job
scalableminds/webknossos pull request #7820
Opened 2024-05-23 09:29 UTC by Tobias314

### Steps to test:
- Checkout the corresponding vocxelytics PR and start the worker. Afterwards, open a dataset in you local Webknossos and select alignment from the AI tools

### Issues:
- fixes #3536

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Needs datastore update after deployment
- [ ] Removed dev-only changes like prints and application.conf edits
- [] Considered [common edge cases](https://github.com/scalableminds/webknossos/blob/master/.github/common_edge_cases.md)

2024-06-03 13:06 UTC, Tobias314 commented
> Where does the align_example.jpg come from? Did you double-check that we may publish this data?

The pictures can also be found on our website ([https://scalableminds.com/alignment-service](https://scalableminds.com/alignment-service)) so that should not be a problem. 

> Do the left and right side really point to the same data? (The blood vessel on the right is so bright, I would have expected to see something of that in the non-aligned version too).

It is not the same picture on the left and on the right but rather one dataset with the left side showing the left section of the dataset in the unaligned state and the right side showing the right section of the dataset in the aligned state.

2024-06-03 13:12 UTC, fm3 commented
> The pictures can also be found on our website so that should not be a problem.

Ok, yes these were checked :)

> It is not the same picture on the left and on the right but rather one dataset with the left side showing the left section of the dataset in the unaligned state and the right side showing the right section of the dataset in the aligned state.

Fair enough. I would have expected a before→after image, of the same crop, but it’s not very important. Feel free to leave it as is for the moment, maybe we’ll insert a more refined image later.

2024-06-05 14:57 UTC, MichaelBuessemeyer requested changes
Thanks for applying my suggestions :t-rex: 

I found a few other things, which I did not notice in the first review round. Please also fix them. Then the code should be fine :)

2024-06-05 14:57 UTC, MichaelBuessemeyer commented on frontend/javascripts/oxalis/view/action-bar/starting_job_modals.tsx
> +  const isSuperUser = useSelector((state: OxalisState) => state.activeUser?.isSuperUser || false);
Awesome, thanks :tada:

2024-06-05 14:57 UTC, MichaelBuessemeyer commented on frontend/javascripts/oxalis/view/action-bar/starting_job_modals.tsx
> +                disabled={!Store.getState().activeUser?.isSuperUser}
Here is still a access to the `isSuperUser` field of the active user, although it was already selected above. You can just use the selected `isSuperUser` variable.
```suggestion
                disabled={!isSuperUser}
```

2024-06-05 14:57 UTC, MichaelBuessemeyer commented on frontend/javascripts/oxalis/view/action-bar/starting_job_modals.tsx
> +                onClick={() => Store.dispatch(setAIJobModalStateAction("align_sections"))}
And here is still a`Store.dispatch`
```suggestion
                onClick={() => dispatch(setAIJobModalStateAction("align_sections"))}
```

2024-06-05 14:57 UTC, MichaelBuessemeyer commented on frontend/javascripts/oxalis/view/action-bar/starting_job_modals.tsx
> +                        alt={"Mitochondria detection example"}
This should be renamed to something like
```suggestion
                        alt={"Example of improved alignment of slices"}
```

2024-06-06 14:56 UTC, MichaelBuessemeyer approved these changes
The frontend code looks good to me :tada:

2024-06-11 09:23 UTC, merged