[WIP] Open experimental alignment services to public
scalableminds/webknossos pull request #8026
Opened 2024-08-23 13:08 UTC by philippotto

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- abc

### TODOs:
- [X] extend docs
- [X] adapt alignment banner
- [X] fine-tune styling
- [ ] wait for RAM-optimized alignment worker
- [ ] remove temporary code changes

### Issues:
- contributes #7955

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

2024-09-12 13:57 UTC, hotzenklotz requested changes
There are various commented out sections that are likely meant to be undone before merging, right?

2024-09-12 13:57 UTC, hotzenklotz commented on .circleci/not-on-master.sh
> +# if [ "${CIRCLE_BRANCH}" == "master" ]; then
Undo?

2024-09-12 13:57 UTC, hotzenklotz commented on conf/application.conf
> +  isWkorgInstance = true
Undo!

2024-09-12 13:57 UTC, hotzenklotz commented on frontend/javascripts/admin/dataset/dataset_add_view.tsx
> +  // segmentationBanner,
Undo?

2024-09-12 13:57 UTC, hotzenklotz commented on frontend/javascripts/admin/dataset/dataset_add_view.tsx
> +  // if (!features().isWkorgInstance) {
Undo?

2024-09-12 14:13 UTC, philippotto commented
> There are various commented out sections that are likely meant to be undone before merging, right?

yes, this was meant to make testing easier. if you are fine with the current state of the UI and wording, I'll undo the temporary changes.

2024-09-16 07:38 UTC, hotzenklotz approved these changes

2024-09-16 07:47 UTC, merged