Faster Mesh Rendering and Raycasting in 3D viewport
scalableminds/webknossos pull request #8106
Opened 2024-10-01 08:25 UTC by daniel-wer

Initially started in a Hackathon project in 2024.

- Uses [Bounding Volume Hierarchies (BVH)](https://github.com/gkjohnson/three-mesh-bvh) for optimized raycasting
- As a requisite to the bvh package, geometries of a single (agglomerate) mesh are now merged into one geometry. This also saves draw calls.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- load precomputed and adhoc meshes and interact with them
- also use the proofreading tool (activate an hdf5 mapping and do splits/merges with the meshes)

### TODOs:
- [x] Restore 3D Viewport Proofreading
- [x] Mesh Colors changed after threeJS update

### Issues:
- fixes #7832 

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

2024-10-03 14:13 UTC, daniel-wer commented
Thanks for updating the title and PR description @fm3 :)

I'll continue with restoring the 3D viewport proofreading using vertex colors once I'm back in office. I'll also have a look at the washed out colors then.

2025-03-10 10:28 UTC, daniel-wer commented on package.json
> +    "three-mesh-bvh": "^0.8.1",
Was not intentional, 0.9.0 has not been out at the time

2025-03-28 13:22 UTC, MichaelBuessemeyer requested changes
Ok this wasn't very easy to get my head around. But what I understood now is that you optimized the "chunked meshes" in proofreading mode away so that a mesh has no sub meshes anymore and instead the selective "sub mesh highlighting" is done via the vertex coloring feature (assigning the correct vertices a different color to highlight the sub mesh)? Is that correct? 

This was also necessary nessecity as the PR description states, correct?

Please find my code review comments below :D

2025-03-28 13:22 UTC, MichaelBuessemeyer commented on frontend/javascripts/oxalis/view/plane_view.ts
> +    const after = performance.now();
I'd say the performance measurement should be removed after this pr

2025-03-28 13:22 UTC, MichaelBuessemeyer commented on frontend/javascripts/oxalis/view/plane_view.ts
> +      console.log("raycast took", after - before, "ms");
and also remove this :D

2025-03-28 13:43 UTC, MichaelBuessemeyer commented
During testing I noticed that it is possible to hover a mesh even when the rendered viewports are in the way (my mouse is not rendered in the screenshot :/): 
![image](https://github.com/user-attachments/assets/24806502-7576-4361-9f5b-228a0bbbd0c3)

But some testing showed me that this is also the case on the master. Do you think it makes sense to make the rendered viewport planes "blocking" the raycasting in case they are configured? Would be a candidate for a new issue imo.

Besides this, I noticed that rendering precomputed meshes is broken in the current state. They shortly flicker into being rendered for a few frames when loaded and afterwards they are no longer rendered :ghost:

2025-04-03 12:00 UTC, philippotto commented on frontend/javascripts/oxalis/controller/mesh_helpers.ts
> +    this.cumulativeStartPosition.push(cumsum);
> last entry could be duplicated in case the last bufferGeometry has also a new unmapped segment id.

a strict duplicate should never happen, because even if isNewSegmentId is true in the last iteration, cumsum will still be incremented by the position count. I think, this is the typical way of maintaining an offsets table (the last entry is usually the index at which new data *could* be appended or where existing data ends).

> So this behaviour is actually useful for getRangeForPosition to not return something out of range with this.cumulativeStartPosition[index + 1]?

yes, that's true.

2025-04-03 16:21 UTC, philippotto commented on frontend/javascripts/oxalis/controller/segment_mesh_controller.ts
> +    geometry.setAttribute("color", new THREE.BufferAttribute(colorBuffer, 3));
"color" is a buffer attribute on the geometry. I don't think it can be passed to the material. or did I misunderstand you?

2025-04-03 16:26 UTC, philippotto commented on frontend/javascripts/oxalis/controller/segment_mesh_controller.ts
> +      mesh.geometry.attributes.color.needsUpdate = true;
the color of the mesh is either uniform (material.color) if vertexColors is false OR it is defined by the color buffer attribute (if vertexColors is true). the code here is about the latter case. I pushed a new commit that clarifies that a bit. WHITE only needs to be set so that the vertex colors have precedence.

2025-04-03 16:29 UTC, philippotto commented on frontend/javascripts/oxalis/controller/segment_mesh_controller.ts
> +    setColor();
yes, good point. I think this code grew historically :)

2025-04-04 08:09 UTC, philippotto commented on frontend/javascripts/oxalis/api/wk_dev.ts
> +  async benchmarkRotate() {
I enabled the FPS meter and monitored that manually, but thanks for pointing this out as it's really suboptimal. I improved the code now so that it also emits measurements :)

2025-04-04 08:27 UTC, philippotto commented on frontend/javascripts/oxalis/controller/segment_mesh_controller.ts
> +                setRangeToColor(child.geometry, null, colorArray);
you are right that we wouldn't need to use vertexColors in that particular case. however, the code is written so that using vertex colors for a uniform color still works and does not cause problems. we could probably switch to non-vertexcolors more often, but I haven't seen indications that this hinders performance much, which is why I'd like to keep it as is for now. 
the entire module could still use further refactoring at some point in the future and then improving this is probably a good idea.

2025-04-04 11:57 UTC, philippotto commented on frontend/javascripts/oxalis/view/right-border-tabs/segments_tab/segments_view.tsx
> +          });
thanks for putting the finger in the wound. it was meant as a quick workaround, but you are right, that this is suboptimal. I just pushed cc187636bf which refactors `this.state.groupsSegmentsVisibilityStateMap` away. the state was only necessary for rendering the context menu which was overkill anyway.

2025-04-04 12:19 UTC, philippotto commented
@MichaelBuessemeyer Thank you for your valuable feedback! And sorry about the whole todop comments. I must have mistakenly thought that I already self-reviewed the PR when I in fact did not. Please have another look. I incorporated/commented on your feedback :)

2025-04-08 13:22 UTC, MichaelBuessemeyer requested changes
Thanks a lot for taking care of all my comments :pray: 

But I am terribly sorry: I found another bug that looks pretty tedious to debug. Here is the video of me reproducing this:

https://github.com/user-attachments/assets/2bdd35a8-c8b1-4e5f-b759-21fd9806e49f

I gave this a little more time to get more details on how to reproduce:
- I use the l4_sample v2 dataset with mapping 80 turned on
- Load one precomputed mesh next to the other mesh you want to load
- Load the other mesh ad hoc and set its opacity < 1.
- Then you can observe the strange rendering behaviour.

The same should also be reproducable when loading (1st ad-hoc & 2nd precomputed). But if you use only ad-hoc or only precomputed, this bug does not occur

2025-04-08 14:09 UTC, MichaelBuessemeyer commented
> But I am terribly sorry: I found another bug that looks pretty tedious to debug. Here is the video of me reproducing this:

Ok turns out, this is already buggy on the current master :/ So I'd say this isn't a must fix before merging this PR :+1: 


But I did some more testing an ended up with a mesh in a rendered state that does not support highlighting on hover :thinking: 

https://github.com/user-attachments/assets/41d77856-fefd-4d53-9eb7-e2ece95f1239


I found 2 strange behaviour out of which the 1st is known to me: When the user loads a ad-hoc mesh & precomputed for the same user, the hovering is off, as both meshes exist in the scene.

The second one is that the mesh is rendered in the scene but now hoverable (see at the end)

But here as well: I am not sure whether this PR is responsible for this behaviour. IMO this shouldn't block this PR as the reproduction steps are a bit of try an error loading the same mesh as ad-hoc / precomputed over and over again and deleting it. So this strange behaviour shouldn't really impact our users.

What do you think @philippotto I would vote for creating an issue for this

2025-04-08 15:51 UTC, philippotto commented on frontend/javascripts/oxalis/controller/mesh_helpers.ts
> +    this.cumulativeStartPosition.push(cumsum);
> So there is a term for this fancy data structure.

I call it "offsets table" but googling that term doesn't bring up good results :see_no_evil: not sure whether it has a proper name. in the end, it is an array of offsets (that point to another array) :shrug: 

I added a docstring to the class now which hopefully explains its purpose and how it works better :)

2025-04-09 09:25 UTC, MichaelBuessemeyer approved these changes
Thanks for implementing all the feedback :pray:

During testing I could no longer reproduced the [second bug](https://github.com/scalableminds/webknossos/pull/8106#issuecomment-2786583705) :tada: 

But the [first one](https://github.com/scalableminds/webknossos/pull/8106#pullrequestreview-2749675909)  still exists :/. But as this is already the case on the master and the opacity feature is new I'd say it is ok if we fix this in a follow up. This shouldn't block this PR imo

2025-04-09 12:49 UTC, philippotto commented
thanks for having another look! will merge now :)

> But the [first one](https://github.com/scalableminds/webknossos/pull/8106#pullrequestreview-2749675909) still exists :/. But as this is already the case on the master and the opacity feature is new I'd say it is ok if we fix this in a follow up. This shouldn't block this PR imo

yes, I think, that's orthogonal to this PR.

2025-04-09 13:03 UTC, merged